name: Deploy Monorepo to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Docusaurus and Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Turbo
        run: npm install turbo --global

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: turbo run build --filter=docs

      - name: Build Next.js
        run: turbo run build --filter=web

      - name: Deploy Docusaurus to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/build # Docusaurus 出力ディレクトリ
          user_name: "tsutom-t"
          user_email: "takatop162@gmail.com"

      - name: Deploy Next.js to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/web/out # Next.js 出力ディレクトリ
          user_name: "tsutom-t"
          user_email: "takatop162@gmail.com"
